// スクリーニング用デモデータ

import { StockMetrics, scoreStocks, ScoredStock } from './scoring';

// Re-export ScoredStock for use in other modules
export type { ScoredStock } from './scoring';

// セクター定義
export const SECTORS = [
  'テクノロジー',
  'ヘルスケア',
  '金融',
  '一般消費財',
  '資本財',
  'エネルギー',
  '生活必需品',
  '公益事業',
  '素材',
  '通信',
  '不動産'
] as const;

export type Sector = typeof SECTORS[number];

// テーマタグ定義
export const THEME_TAGS = [
  'AI',
  '半導体',
  'EV',
  'クラウド',
  'フィンテック',
  'バイオテック',
  '再生可能エネルギー',
  'メタバース',
  '5G',
  'サイバーセキュリティ',
  'ヘルステック',
  'Eコマース',
  '配当貴族',
  'ESG',
  'GAFAM'
] as const;

export type ThemeTag = typeof THEME_TAGS[number];

// デモ用の銘柄データ
const demoStocksData: StockMetrics[] = [
  {
    symbol: 'AAPL',
    name: 'Apple Inc.',
    sector: 'テクノロジー',
    price: 178.50,
    change: 2.35,
    changePercent: 1.33,
    marketCap: 2850000,
    per: 28.5,
    pbr: 45.2,
    peg: 2.1,
    roe: 147.5,
    epsGrowth3Y: 12.5,
    epsGrowth5Y: 18.3,
    revenueGrowth: 8.1,
    operatingMargin: 29.8,
    equityRatio: 17.8,
    currentRatio: 0.94,
    debtRatio: 195.2,
    operatingCashFlow: 118287,
    dividendYield: 0.5,
    consecutiveDividendYears: 11,
    payoutRatio: 15.2,
    priceVs50MA: 3.2,
    priceVs200MA: 12.5,
    rsi: 58,
    macdSignal: 'bullish',
    volumeChange: 5.2,
    tags: ['AI', 'GAFAM']
  },
  {
    symbol: 'MSFT',
    name: 'Microsoft Corporation',
    sector: 'テクノロジー',
    price: 378.20,
    change: 5.80,
    changePercent: 1.56,
    marketCap: 2810000,
    per: 35.2,
    pbr: 12.8,
    peg: 2.5,
    roe: 38.5,
    epsGrowth3Y: 15.8,
    epsGrowth5Y: 22.1,
    revenueGrowth: 15.2,
    operatingMargin: 42.1,
    equityRatio: 41.2,
    currentRatio: 1.77,
    debtRatio: 35.8,
    operatingCashFlow: 87582,
    dividendYield: 0.8,
    consecutiveDividendYears: 18,
    payoutRatio: 27.5,
    priceVs50MA: 5.1,
    priceVs200MA: 18.3,
    rsi: 62,
    macdSignal: 'bullish',
    volumeChange: 8.5,
    tags: ['AI', 'クラウド', 'GAFAM']
  },
  {
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    sector: 'テクノロジー',
    price: 495.80,
    change: 15.20,
    changePercent: 3.16,
    marketCap: 1220000,
    per: 62.5,
    pbr: 38.5,
    peg: 1.2,
    roe: 69.2,
    epsGrowth3Y: 58.5,
    epsGrowth5Y: 52.1,
    revenueGrowth: 122.5,
    operatingMargin: 54.1,
    equityRatio: 65.8,
    currentRatio: 4.17,
    debtRatio: 15.2,
    operatingCashFlow: 18848,
    dividendYield: 0.04,
    consecutiveDividendYears: 6,
    payoutRatio: 2.5,
    priceVs50MA: 12.5,
    priceVs200MA: 85.2,
    rsi: 72,
    macdSignal: 'bullish',
    volumeChange: 25.8,
    tags: ['AI', '半導体']
  },
  {
    symbol: 'GOOGL',
    name: 'Alphabet Inc.',
    sector: 'テクノロジー',
    price: 141.50,
    change: 1.85,
    changePercent: 1.32,
    marketCap: 1780000,
    per: 24.2,
    pbr: 6.1,
    peg: 1.1,
    roe: 25.8,
    epsGrowth3Y: 18.5,
    epsGrowth5Y: 21.2,
    revenueGrowth: 10.8,
    operatingMargin: 27.5,
    equityRatio: 72.5,
    currentRatio: 2.38,
    debtRatio: 5.8,
    operatingCashFlow: 101746,
    dividendYield: 0.0,
    consecutiveDividendYears: 0,
    payoutRatio: 0,
    priceVs50MA: 2.8,
    priceVs200MA: 15.2,
    rsi: 55,
    macdSignal: 'bullish',
    volumeChange: 3.5,
    tags: ['AI', 'クラウド', 'GAFAM']
  },
  {
    symbol: 'AMZN',
    name: 'Amazon.com Inc.',
    sector: '一般消費財',
    price: 178.50,
    change: 3.20,
    changePercent: 1.83,
    marketCap: 1860000,
    per: 58.5,
    pbr: 9.2,
    peg: 1.8,
    roe: 16.8,
    epsGrowth3Y: 35.2,
    epsGrowth5Y: 28.5,
    revenueGrowth: 11.8,
    operatingMargin: 6.1,
    equityRatio: 32.8,
    currentRatio: 1.05,
    debtRatio: 62.5,
    operatingCashFlow: 84946,
    dividendYield: 0.0,
    consecutiveDividendYears: 0,
    payoutRatio: 0,
    priceVs50MA: 4.2,
    priceVs200MA: 22.5,
    rsi: 58,
    macdSignal: 'bullish',
    volumeChange: 12.5,
    tags: ['AI', 'クラウド', 'Eコマース', 'GAFAM']
  },
  {
    symbol: 'META',
    name: 'Meta Platforms Inc.',
    sector: 'テクノロジー',
    price: 505.50,
    change: 8.50,
    changePercent: 1.71,
    marketCap: 1290000,
    per: 26.8,
    pbr: 8.5,
    peg: 0.9,
    roe: 31.5,
    epsGrowth3Y: 28.5,
    epsGrowth5Y: 22.8,
    revenueGrowth: 21.5,
    operatingMargin: 35.2,
    equityRatio: 61.5,
    currentRatio: 2.68,
    debtRatio: 18.5,
    operatingCashFlow: 71113,
    dividendYield: 0.4,
    consecutiveDividendYears: 1,
    payoutRatio: 10.5,
    priceVs50MA: 8.5,
    priceVs200MA: 35.2,
    rsi: 65,
    macdSignal: 'bullish',
    volumeChange: 15.2,
    tags: ['AI', 'メタバース', 'GAFAM']
  },
  {
    symbol: 'TSLA',
    name: 'Tesla Inc.',
    sector: '一般消費財',
    price: 245.80,
    change: -5.20,
    changePercent: -2.07,
    marketCap: 780000,
    per: 65.2,
    pbr: 12.5,
    peg: 3.5,
    roe: 21.8,
    epsGrowth3Y: 85.2,
    epsGrowth5Y: 125.5,
    revenueGrowth: 18.8,
    operatingMargin: 11.2,
    equityRatio: 42.5,
    currentRatio: 1.73,
    debtRatio: 8.5,
    operatingCashFlow: 13256,
    dividendYield: 0.0,
    consecutiveDividendYears: 0,
    payoutRatio: 0,
    priceVs50MA: -5.2,
    priceVs200MA: 8.5,
    rsi: 42,
    macdSignal: 'bearish',
    volumeChange: -8.5,
    tags: ['EV', '再生可能エネルギー', 'AI']
  },
  {
    symbol: 'JNJ',
    name: 'Johnson & Johnson',
    sector: 'ヘルスケア',
    price: 158.20,
    change: 0.85,
    changePercent: 0.54,
    marketCap: 380000,
    per: 15.8,
    pbr: 5.2,
    peg: 2.8,
    roe: 22.5,
    epsGrowth3Y: 5.2,
    epsGrowth5Y: 6.8,
    revenueGrowth: 3.5,
    operatingMargin: 24.8,
    equityRatio: 42.8,
    currentRatio: 1.15,
    debtRatio: 38.5,
    operatingCashFlow: 22780,
    dividendYield: 2.9,
    consecutiveDividendYears: 61,
    payoutRatio: 45.2,
    priceVs50MA: 1.2,
    priceVs200MA: 2.5,
    rsi: 48,
    macdSignal: 'neutral',
    volumeChange: -2.5,
    tags: ['配当貴族', 'ヘルステック']
  },
  {
    symbol: 'JPM',
    name: 'JPMorgan Chase & Co.',
    sector: '金融',
    price: 195.80,
    change: 2.15,
    changePercent: 1.11,
    marketCap: 565000,
    per: 11.2,
    pbr: 1.8,
    peg: 1.5,
    roe: 15.2,
    epsGrowth3Y: 8.5,
    epsGrowth5Y: 12.2,
    revenueGrowth: 18.5,
    operatingMargin: 38.2,
    equityRatio: 8.5,
    currentRatio: 1.2,
    debtRatio: 250.5,
    operatingCashFlow: 45892,
    dividendYield: 2.3,
    consecutiveDividendYears: 13,
    payoutRatio: 25.8,
    priceVs50MA: 3.5,
    priceVs200MA: 18.5,
    rsi: 55,
    macdSignal: 'bullish',
    volumeChange: 5.8,
    tags: ['フィンテック', '配当貴族']
  },
  {
    symbol: 'V',
    name: 'Visa Inc.',
    sector: '金融',
    price: 278.50,
    change: 3.25,
    changePercent: 1.18,
    marketCap: 565000,
    per: 28.5,
    pbr: 13.2,
    peg: 1.6,
    roe: 48.5,
    epsGrowth3Y: 15.2,
    epsGrowth5Y: 18.5,
    revenueGrowth: 10.5,
    operatingMargin: 67.2,
    equityRatio: 35.8,
    currentRatio: 1.45,
    debtRatio: 58.2,
    operatingCashFlow: 19738,
    dividendYield: 0.8,
    consecutiveDividendYears: 15,
    payoutRatio: 22.5,
    priceVs50MA: 2.8,
    priceVs200MA: 8.5,
    rsi: 52,
    macdSignal: 'bullish',
    volumeChange: 2.5,
    tags: ['フィンテック']
  },
  {
    symbol: 'UNH',
    name: 'UnitedHealth Group Inc.',
    sector: 'ヘルスケア',
    price: 525.80,
    change: 5.50,
    changePercent: 1.06,
    marketCap: 485000,
    per: 22.5,
    pbr: 6.8,
    peg: 1.4,
    roe: 25.8,
    epsGrowth3Y: 12.5,
    epsGrowth5Y: 15.2,
    revenueGrowth: 12.8,
    operatingMargin: 8.5,
    equityRatio: 31.2,
    currentRatio: 0.78,
    debtRatio: 68.5,
    operatingCashFlow: 29108,
    dividendYield: 1.4,
    consecutiveDividendYears: 14,
    payoutRatio: 30.5,
    priceVs50MA: 1.5,
    priceVs200MA: 5.2,
    rsi: 50,
    macdSignal: 'neutral',
    volumeChange: 0.5,
    tags: ['ヘルステック']
  },
  {
    symbol: 'HD',
    name: 'The Home Depot Inc.',
    sector: '一般消費財',
    price: 345.20,
    change: 4.80,
    changePercent: 1.41,
    marketCap: 345000,
    per: 23.5,
    pbr: 125.5,
    peg: 2.2,
    roe: 520.5,
    epsGrowth3Y: 8.2,
    epsGrowth5Y: 12.5,
    revenueGrowth: 2.5,
    operatingMargin: 15.2,
    equityRatio: 2.8,
    currentRatio: 1.25,
    debtRatio: 985.2,
    operatingCashFlow: 16852,
    dividendYield: 2.5,
    consecutiveDividendYears: 14,
    payoutRatio: 58.5,
    priceVs50MA: 2.2,
    priceVs200MA: 8.5,
    rsi: 55,
    macdSignal: 'bullish',
    volumeChange: 3.5,
    tags: ['配当貴族']
  },
  {
    symbol: 'PG',
    name: 'Procter & Gamble Co.',
    sector: '生活必需品',
    price: 158.80,
    change: 0.95,
    changePercent: 0.60,
    marketCap: 375000,
    per: 26.2,
    pbr: 8.5,
    peg: 3.8,
    roe: 32.5,
    epsGrowth3Y: 6.8,
    epsGrowth5Y: 8.2,
    revenueGrowth: 3.2,
    operatingMargin: 22.5,
    equityRatio: 32.5,
    currentRatio: 0.72,
    debtRatio: 62.5,
    operatingCashFlow: 16768,
    dividendYield: 2.4,
    consecutiveDividendYears: 67,
    payoutRatio: 62.5,
    priceVs50MA: 0.5,
    priceVs200MA: 2.2,
    rsi: 45,
    macdSignal: 'neutral',
    volumeChange: -1.5,
    tags: ['配当貴族', 'ESG']
  },
  {
    symbol: 'KO',
    name: 'Coca-Cola Company',
    sector: '生活必需品',
    price: 62.50,
    change: 0.35,
    changePercent: 0.56,
    marketCap: 270000,
    per: 24.8,
    pbr: 11.2,
    peg: 3.5,
    roe: 42.5,
    epsGrowth3Y: 7.2,
    epsGrowth5Y: 5.8,
    revenueGrowth: 5.5,
    operatingMargin: 28.5,
    equityRatio: 21.8,
    currentRatio: 1.15,
    debtRatio: 158.5,
    operatingCashFlow: 11882,
    dividendYield: 3.0,
    consecutiveDividendYears: 61,
    payoutRatio: 72.5,
    priceVs50MA: 1.2,
    priceVs200MA: 3.5,
    rsi: 48,
    macdSignal: 'neutral',
    volumeChange: 0.5,
    tags: ['配当貴族', 'ESG']
  },
  {
    symbol: 'AMD',
    name: 'Advanced Micro Devices Inc.',
    sector: 'テクノロジー',
    price: 145.80,
    change: 5.20,
    changePercent: 3.70,
    marketCap: 235000,
    per: 125.5,
    pbr: 4.8,
    peg: 0.8,
    roe: 3.8,
    epsGrowth3Y: 85.2,
    epsGrowth5Y: 145.5,
    revenueGrowth: 45.2,
    operatingMargin: 5.2,
    equityRatio: 58.5,
    currentRatio: 2.52,
    debtRatio: 5.8,
    operatingCashFlow: 1418,
    dividendYield: 0.0,
    consecutiveDividendYears: 0,
    payoutRatio: 0,
    priceVs50MA: 8.5,
    priceVs200MA: 25.2,
    rsi: 68,
    macdSignal: 'bullish',
    volumeChange: 35.2,
    tags: ['AI', '半導体']
  },
  {
    symbol: 'AVGO',
    name: 'Broadcom Inc.',
    sector: 'テクノロジー',
    price: 1285.50,
    change: 25.80,
    changePercent: 2.05,
    marketCap: 595000,
    per: 35.2,
    pbr: 11.5,
    peg: 1.5,
    roe: 35.2,
    epsGrowth3Y: 22.5,
    epsGrowth5Y: 28.8,
    revenueGrowth: 42.5,
    operatingMargin: 45.8,
    equityRatio: 32.8,
    currentRatio: 2.82,
    debtRatio: 105.2,
    operatingCashFlow: 18789,
    dividendYield: 1.6,
    consecutiveDividendYears: 14,
    payoutRatio: 55.2,
    priceVs50MA: 10.5,
    priceVs200MA: 52.8,
    rsi: 65,
    macdSignal: 'bullish',
    volumeChange: 18.5,
    tags: ['AI', '半導体']
  },
  {
    symbol: 'CRM',
    name: 'Salesforce Inc.',
    sector: 'テクノロジー',
    price: 285.20,
    change: 4.50,
    changePercent: 1.60,
    marketCap: 275000,
    per: 48.5,
    pbr: 4.2,
    peg: 1.8,
    roe: 8.8,
    epsGrowth3Y: 28.5,
    epsGrowth5Y: 22.5,
    revenueGrowth: 11.2,
    operatingMargin: 17.5,
    equityRatio: 62.5,
    currentRatio: 1.02,
    debtRatio: 15.8,
    operatingCashFlow: 9288,
    dividendYield: 0.0,
    consecutiveDividendYears: 0,
    payoutRatio: 0,
    priceVs50MA: 5.2,
    priceVs200MA: 22.5,
    rsi: 58,
    macdSignal: 'bullish',
    volumeChange: 8.5,
    tags: ['AI', 'クラウド']
  },
  {
    symbol: 'COST',
    name: 'Costco Wholesale Corp.',
    sector: '生活必需品',
    price: 785.50,
    change: 8.20,
    changePercent: 1.05,
    marketCap: 350000,
    per: 48.5,
    pbr: 14.2,
    peg: 3.5,
    roe: 30.5,
    epsGrowth3Y: 12.8,
    epsGrowth5Y: 14.5,
    revenueGrowth: 8.5,
    operatingMargin: 3.5,
    equityRatio: 35.8,
    currentRatio: 1.02,
    debtRatio: 28.5,
    operatingCashFlow: 8258,
    dividendYield: 0.6,
    consecutiveDividendYears: 19,
    payoutRatio: 28.5,
    priceVs50MA: 2.5,
    priceVs200MA: 12.8,
    rsi: 52,
    macdSignal: 'bullish',
    volumeChange: 2.5,
    tags: ['ESG']
  },
  {
    symbol: 'XOM',
    name: 'Exxon Mobil Corporation',
    sector: 'エネルギー',
    price: 112.50,
    change: -1.25,
    changePercent: -1.10,
    marketCap: 450000,
    per: 12.5,
    pbr: 2.1,
    peg: 1.8,
    roe: 18.5,
    epsGrowth3Y: 45.2,
    epsGrowth5Y: 25.8,
    revenueGrowth: 8.5,
    operatingMargin: 15.2,
    equityRatio: 52.5,
    currentRatio: 1.42,
    debtRatio: 22.5,
    operatingCashFlow: 55268,
    dividendYield: 3.3,
    consecutiveDividendYears: 41,
    payoutRatio: 42.5,
    priceVs50MA: -2.5,
    priceVs200MA: 5.2,
    rsi: 42,
    macdSignal: 'bearish',
    volumeChange: -5.8,
    tags: ['配当貴族']
  },
  {
    symbol: 'LLY',
    name: 'Eli Lilly and Company',
    sector: 'ヘルスケア',
    price: 785.20,
    change: 12.50,
    changePercent: 1.62,
    marketCap: 745000,
    per: 85.2,
    pbr: 52.5,
    peg: 1.2,
    roe: 68.5,
    epsGrowth3Y: 55.2,
    epsGrowth5Y: 42.8,
    revenueGrowth: 32.5,
    operatingMargin: 28.5,
    equityRatio: 18.5,
    currentRatio: 1.18,
    debtRatio: 185.2,
    operatingCashFlow: 8952,
    dividendYield: 0.7,
    consecutiveDividendYears: 9,
    payoutRatio: 58.5,
    priceVs50MA: 8.2,
    priceVs200MA: 45.2,
    rsi: 68,
    macdSignal: 'bullish',
    volumeChange: 22.5,
    tags: ['バイオテック', 'ヘルステック']
  },
  {
    symbol: 'ABBV',
    name: 'AbbVie Inc.',
    sector: 'ヘルスケア',
    price: 175.80,
    change: 2.15,
    changePercent: 1.24,
    marketCap: 310000,
    per: 18.5,
    pbr: 22.5,
    peg: 1.8,
    roe: 125.5,
    epsGrowth3Y: 8.5,
    epsGrowth5Y: 12.2,
    revenueGrowth: 5.8,
    operatingMargin: 32.5,
    equityRatio: 8.5,
    currentRatio: 0.82,
    debtRatio: 385.2,
    operatingCashFlow: 22458,
    dividendYield: 3.5,
    consecutiveDividendYears: 51,
    payoutRatio: 65.2,
    priceVs50MA: 3.5,
    priceVs200MA: 12.5,
    rsi: 55,
    macdSignal: 'bullish',
    volumeChange: 5.2,
    tags: ['バイオテック', '配当貴族', 'ヘルステック']
  },
  {
    symbol: 'MRK',
    name: 'Merck & Co. Inc.',
    sector: 'ヘルスケア',
    price: 125.50,
    change: 1.85,
    changePercent: 1.50,
    marketCap: 320000,
    per: 18.2,
    pbr: 6.5,
    peg: 1.2,
    roe: 38.5,
    epsGrowth3Y: 12.5,
    epsGrowth5Y: 15.8,
    revenueGrowth: 8.5,
    operatingMargin: 28.5,
    equityRatio: 35.8,
    currentRatio: 1.35,
    debtRatio: 65.2,
    operatingCashFlow: 15892,
    dividendYield: 2.5,
    consecutiveDividendYears: 12,
    payoutRatio: 45.2,
    priceVs50MA: 2.8,
    priceVs200MA: 8.5,
    rsi: 52,
    macdSignal: 'bullish',
    volumeChange: 3.5,
    tags: ['バイオテック', 'ヘルステック']
  },
  {
    symbol: 'INTC',
    name: 'Intel Corporation',
    sector: 'テクノロジー',
    price: 42.50,
    change: -0.85,
    changePercent: -1.96,
    marketCap: 180000,
    per: 85.2,
    pbr: 1.8,
    peg: -2.5,
    roe: 2.2,
    epsGrowth3Y: -25.5,
    epsGrowth5Y: -15.2,
    revenueGrowth: -15.8,
    operatingMargin: 2.5,
    equityRatio: 55.8,
    currentRatio: 1.58,
    debtRatio: 48.5,
    operatingCashFlow: 11892,
    dividendYield: 1.2,
    consecutiveDividendYears: 8,
    payoutRatio: 125.5,
    priceVs50MA: -8.5,
    priceVs200MA: -15.2,
    rsi: 32,
    macdSignal: 'bearish',
    volumeChange: -12.5,
    tags: ['半導体']
  },
  {
    symbol: 'T',
    name: 'AT&T Inc.',
    sector: '通信',
    price: 18.50,
    change: 0.15,
    changePercent: 0.82,
    marketCap: 132000,
    per: 8.5,
    pbr: 1.2,
    peg: 1.5,
    roe: 14.2,
    epsGrowth3Y: -5.2,
    epsGrowth5Y: -8.5,
    revenueGrowth: -2.5,
    operatingMargin: 18.5,
    equityRatio: 28.5,
    currentRatio: 0.62,
    debtRatio: 128.5,
    operatingCashFlow: 26892,
    dividendYield: 5.8,
    consecutiveDividendYears: 38,
    payoutRatio: 48.5,
    priceVs50MA: 2.5,
    priceVs200MA: -5.2,
    rsi: 45,
    macdSignal: 'neutral',
    volumeChange: 2.5,
    tags: ['5G', '配当貴族']
  },
  {
    symbol: 'VZ',
    name: 'Verizon Communications Inc.',
    sector: '通信',
    price: 42.80,
    change: 0.35,
    changePercent: 0.82,
    marketCap: 180000,
    per: 9.2,
    pbr: 1.8,
    peg: 2.5,
    roe: 20.5,
    epsGrowth3Y: 2.5,
    epsGrowth5Y: 1.8,
    revenueGrowth: 1.5,
    operatingMargin: 22.5,
    equityRatio: 22.5,
    currentRatio: 0.78,
    debtRatio: 185.2,
    operatingCashFlow: 36892,
    dividendYield: 6.2,
    consecutiveDividendYears: 19,
    payoutRatio: 55.2,
    priceVs50MA: 0.5,
    priceVs200MA: -2.5,
    rsi: 42,
    macdSignal: 'neutral',
    volumeChange: -2.5,
    tags: ['5G', '配当貴族']
  },
  {
    symbol: 'NEE',
    name: 'NextEra Energy Inc.',
    sector: '公益事業',
    price: 75.80,
    change: 1.25,
    changePercent: 1.68,
    marketCap: 155000,
    per: 22.5,
    pbr: 3.2,
    peg: 2.2,
    roe: 14.5,
    epsGrowth3Y: 10.2,
    epsGrowth5Y: 12.5,
    revenueGrowth: 12.8,
    operatingMargin: 28.5,
    equityRatio: 28.5,
    currentRatio: 0.55,
    debtRatio: 125.5,
    operatingCashFlow: 8892,
    dividendYield: 2.8,
    consecutiveDividendYears: 28,
    payoutRatio: 62.5,
    priceVs50MA: 5.2,
    priceVs200MA: 12.5,
    rsi: 58,
    macdSignal: 'bullish',
    volumeChange: 8.5,
    tags: ['再生可能エネルギー', 'ESG', '配当貴族']
  },
  {
    symbol: 'SHOP',
    name: 'Shopify Inc.',
    sector: 'テクノロジー',
    price: 78.50,
    change: 2.85,
    changePercent: 3.77,
    marketCap: 98000,
    per: 85.2,
    pbr: 12.5,
    peg: 1.5,
    roe: 15.8,
    epsGrowth3Y: 125.5,
    epsGrowth5Y: 85.2,
    revenueGrowth: 28.5,
    operatingMargin: 8.5,
    equityRatio: 82.5,
    currentRatio: 9.52,
    debtRatio: 2.5,
    operatingCashFlow: 1258,
    dividendYield: 0.0,
    consecutiveDividendYears: 0,
    payoutRatio: 0,
    priceVs50MA: 12.5,
    priceVs200MA: 35.2,
    rsi: 65,
    macdSignal: 'bullish',
    volumeChange: 25.5,
    tags: ['Eコマース', 'フィンテック']
  },
  {
    symbol: 'CRWD',
    name: 'CrowdStrike Holdings Inc.',
    sector: 'テクノロジー',
    price: 285.50,
    change: 8.50,
    changePercent: 3.07,
    marketCap: 68000,
    per: 285.5,
    pbr: 28.5,
    peg: 2.2,
    roe: 10.5,
    epsGrowth3Y: 85.2,
    epsGrowth5Y: 125.5,
    revenueGrowth: 35.2,
    operatingMargin: 5.2,
    equityRatio: 45.8,
    currentRatio: 1.82,
    debtRatio: 32.5,
    operatingCashFlow: 1158,
    dividendYield: 0.0,
    consecutiveDividendYears: 0,
    payoutRatio: 0,
    priceVs50MA: 8.5,
    priceVs200MA: 28.5,
    rsi: 62,
    macdSignal: 'bullish',
    volumeChange: 18.5,
    tags: ['サイバーセキュリティ', 'クラウド']
  },
  {
    symbol: 'PANW',
    name: 'Palo Alto Networks Inc.',
    sector: 'テクノロジー',
    price: 325.80,
    change: 5.85,
    changePercent: 1.83,
    marketCap: 105000,
    per: 48.5,
    pbr: 18.5,
    peg: 1.2,
    roe: 42.5,
    epsGrowth3Y: 45.2,
    epsGrowth5Y: 55.8,
    revenueGrowth: 18.5,
    operatingMargin: 15.2,
    equityRatio: 28.5,
    currentRatio: 0.85,
    debtRatio: 85.2,
    operatingCashFlow: 2892,
    dividendYield: 0.0,
    consecutiveDividendYears: 0,
    payoutRatio: 0,
    priceVs50MA: 5.2,
    priceVs200MA: 22.5,
    rsi: 55,
    macdSignal: 'bullish',
    volumeChange: 12.5,
    tags: ['サイバーセキュリティ', 'クラウド']
  },
  {
    symbol: 'SNOW',
    name: 'Snowflake Inc.',
    sector: 'テクノロジー',
    price: 185.50,
    change: 5.25,
    changePercent: 2.91,
    marketCap: 62000,
    per: -125.5,
    pbr: 12.5,
    peg: -1.5,
    roe: -8.5,
    epsGrowth3Y: 85.2,
    epsGrowth5Y: 125.5,
    revenueGrowth: 35.8,
    operatingMargin: -25.5,
    equityRatio: 72.5,
    currentRatio: 1.78,
    debtRatio: 12.5,
    operatingCashFlow: 785,
    dividendYield: 0.0,
    consecutiveDividendYears: 0,
    payoutRatio: 0,
    priceVs50MA: 10.5,
    priceVs200MA: 28.5,
    rsi: 62,
    macdSignal: 'bullish',
    volumeChange: 22.5,
    tags: ['AI', 'クラウド']
  }
];

// スコア付きの銘柄データを取得
export function getScoredStocks(): ScoredStock[] {
  return scoreStocks(demoStocksData);
}

// 条件に基づいてフィルタリング
export interface ScreeningConditions {
  // ファンダメンタル
  perMin?: number;
  perMax?: number;
  pbrMin?: number;
  pbrMax?: number;
  pegMin?: number;
  pegMax?: number;
  roeMin?: number;
  epsGrowthMin?: number;
  revenueGrowthMin?: number;
  operatingMarginMin?: number;

  // 財務健全性
  equityRatioMin?: number;
  currentRatioMin?: number;
  debtRatioMax?: number;
  operatingCashFlowPositive?: boolean;

  // 配当
  dividendYieldMin?: number;
  dividendYieldMax?: number;
  consecutiveDividendYearsMin?: number;
  payoutRatioMin?: number;
  payoutRatioMax?: number;

  // テクニカル
  aboveMA50?: boolean;
  aboveMA200?: boolean;
  rsiMin?: number;
  rsiMax?: number;
  macdBullish?: boolean;
  volumeChangeMin?: number;

  // その他
  marketCapMin?: number;
  marketCapMax?: number;
  sectors?: string[];
  tags?: string[];
}

export function filterStocks(
  stocks: ScoredStock[],
  conditions: ScreeningConditions
): ScoredStock[] {
  return stocks.filter(stock => {
    // ファンダメンタル条件
    if (conditions.perMin !== undefined && stock.per < conditions.perMin) return false;
    if (conditions.perMax !== undefined && stock.per > conditions.perMax) return false;
    if (conditions.pbrMin !== undefined && stock.pbr < conditions.pbrMin) return false;
    if (conditions.pbrMax !== undefined && stock.pbr > conditions.pbrMax) return false;
    if (conditions.pegMin !== undefined && stock.peg < conditions.pegMin) return false;
    if (conditions.pegMax !== undefined && stock.peg > conditions.pegMax) return false;
    if (conditions.roeMin !== undefined && stock.roe < conditions.roeMin) return false;
    if (conditions.epsGrowthMin !== undefined && stock.epsGrowth3Y < conditions.epsGrowthMin) return false;
    if (conditions.revenueGrowthMin !== undefined && stock.revenueGrowth < conditions.revenueGrowthMin) return false;
    if (conditions.operatingMarginMin !== undefined && stock.operatingMargin < conditions.operatingMarginMin) return false;

    // 財務健全性
    if (conditions.equityRatioMin !== undefined && stock.equityRatio < conditions.equityRatioMin) return false;
    if (conditions.currentRatioMin !== undefined && stock.currentRatio < conditions.currentRatioMin) return false;
    if (conditions.debtRatioMax !== undefined && stock.debtRatio > conditions.debtRatioMax) return false;
    if (conditions.operatingCashFlowPositive && stock.operatingCashFlow <= 0) return false;

    // 配当条件
    if (conditions.dividendYieldMin !== undefined && stock.dividendYield < conditions.dividendYieldMin) return false;
    if (conditions.dividendYieldMax !== undefined && stock.dividendYield > conditions.dividendYieldMax) return false;
    if (conditions.consecutiveDividendYearsMin !== undefined && stock.consecutiveDividendYears < conditions.consecutiveDividendYearsMin) return false;
    if (conditions.payoutRatioMin !== undefined && stock.payoutRatio < conditions.payoutRatioMin) return false;
    if (conditions.payoutRatioMax !== undefined && stock.payoutRatio > conditions.payoutRatioMax) return false;

    // テクニカル条件
    if (conditions.aboveMA50 && stock.priceVs50MA <= 0) return false;
    if (conditions.aboveMA200 && stock.priceVs200MA <= 0) return false;
    if (conditions.rsiMin !== undefined && stock.rsi < conditions.rsiMin) return false;
    if (conditions.rsiMax !== undefined && stock.rsi > conditions.rsiMax) return false;
    if (conditions.macdBullish && stock.macdSignal !== 'bullish') return false;
    if (conditions.volumeChangeMin !== undefined && stock.volumeChange < conditions.volumeChangeMin) return false;

    // その他の条件
    if (conditions.marketCapMin !== undefined && stock.marketCap < conditions.marketCapMin) return false;
    if (conditions.marketCapMax !== undefined && stock.marketCap > conditions.marketCapMax) return false;
    if (conditions.sectors && conditions.sectors.length > 0 && !conditions.sectors.includes(stock.sector)) return false;
    if (conditions.tags && conditions.tags.length > 0) {
      const hasTag = conditions.tags.some(tag => stock.tags.includes(tag));
      if (!hasTag) return false;
    }

    return true;
  });
}

// プリセット条件
export const PRESET_CONDITIONS: { [key: string]: { name: string; description: string; conditions: ScreeningConditions } } = {
  growth: {
    name: '成長株',
    description: 'EPS成長率15%以上、売上成長率10%以上の高成長銘柄',
    conditions: {
      epsGrowthMin: 15,
      revenueGrowthMin: 10,
      operatingCashFlowPositive: true
    }
  },
  value: {
    name: '割安株',
    description: 'PER20以下、PEG1.5以下の割安銘柄',
    conditions: {
      perMax: 20,
      pegMax: 1.5,
      roeMin: 10
    }
  },
  dividend: {
    name: '高配当株',
    description: '配当利回り2.5%以上、連続増配10年以上の配当銘柄',
    conditions: {
      dividendYieldMin: 2.5,
      consecutiveDividendYearsMin: 10,
      payoutRatioMax: 80
    }
  },
  quality: {
    name: '財務健全株',
    description: '自己資本比率30%以上、流動比率1.2以上の優良銘柄',
    conditions: {
      equityRatioMin: 30,
      currentRatioMin: 1.2,
      debtRatioMax: 100,
      operatingCashFlowPositive: true
    }
  },
  momentum: {
    name: '上昇トレンド株',
    description: '50日/200日MA上抜け、RSI50-70の上昇銘柄',
    conditions: {
      aboveMA50: true,
      aboveMA200: true,
      rsiMin: 50,
      rsiMax: 70,
      macdBullish: true
    }
  },
  ai: {
    name: 'AI関連株',
    description: 'AI関連テーマの銘柄',
    conditions: {
      tags: ['AI']
    }
  },
  semiconductor: {
    name: '半導体株',
    description: '半導体関連テーマの銘柄',
    conditions: {
      tags: ['半導体']
    }
  }
};

// 銘柄を取得（シンボルで検索）
export function getStockBySymbol(symbol: string): ScoredStock | undefined {
  const stocks = getScoredStocks();
  return stocks.find(s => s.symbol.toUpperCase() === symbol.toUpperCase());
}
